name: shared_repos
description: Shared resource repositories for Riverpod 3 demos.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  riverpod: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0
